package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.AccessKeyRecordEntity;
import com.chinasofti.rcloud.domain.AccessKeyRecordEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessKeyRecordEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(AccessKeyRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(AccessKeyRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String accessKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(AccessKeyRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(AccessKeyRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<AccessKeyRecordEntity> selectByExample(AccessKeyRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    AccessKeyRecordEntity selectByPrimaryKey(String accessKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") AccessKeyRecordEntity record, @Param("example") AccessKeyRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") AccessKeyRecordEntity record, @Param("example") AccessKeyRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(AccessKeyRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(AccessKeyRecordEntity record);
}