package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.AccountingCycleRecordEntity;
import com.chinasofti.rcloud.domain.AccountingCycleRecordEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountingCycleRecordEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(AccountingCycleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(AccountingCycleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(AccountingCycleRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(AccountingCycleRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<AccountingCycleRecordEntity> selectByExample(AccountingCycleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    AccountingCycleRecordEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") AccountingCycleRecordEntity record, @Param("example") AccountingCycleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") AccountingCycleRecordEntity record, @Param("example") AccountingCycleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(AccountingCycleRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(AccountingCycleRecordEntity record);
}