package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.ApplicationEntity;
import com.chinasofti.rcloud.domain.ApplicationEntityExample;
import com.chinasofti.rcloud.domain.ApplicationEntityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(ApplicationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(ApplicationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(ApplicationEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(ApplicationEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<ApplicationEntityWithBLOBs> selectByExampleWithBLOBs(ApplicationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<ApplicationEntity> selectByExample(ApplicationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    ApplicationEntityWithBLOBs selectByPrimaryKey(String applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") ApplicationEntityWithBLOBs record, @Param("example") ApplicationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ApplicationEntityWithBLOBs record, @Param("example") ApplicationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") ApplicationEntity record, @Param("example") ApplicationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(ApplicationEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ApplicationEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(ApplicationEntity record);
}