package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.ApplyEntity;
import com.chinasofti.rcloud.domain.ApplyEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(ApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(ApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(ApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(ApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<ApplyEntity> selectByExample(ApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    ApplyEntity selectByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") ApplyEntity record, @Param("example") ApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") ApplyEntity record, @Param("example") ApplyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(ApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_apply
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(ApplyEntity record);
}