package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.ApplicationOrderToBillEntityExample;
import com.chinasofti.rcloud.domain.ApplicationOrderToBillEntityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationOrderToBillEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(ApplicationOrderToBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(ApplicationOrderToBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(ApplicationOrderToBillEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(ApplicationOrderToBillEntityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(ApplicationOrderToBillEntityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<ApplicationOrderToBillEntityKey> selectByExample(ApplicationOrderToBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") ApplicationOrderToBillEntityKey record, @Param("example") ApplicationOrderToBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") ApplicationOrderToBillEntityKey record, @Param("example") ApplicationOrderToBillEntityExample example);
}