package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.ApplicationTypeEntity;
import com.chinasofti.rcloud.domain.ApplicationTypeEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationTypeEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(ApplicationTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(ApplicationTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(ApplicationTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(ApplicationTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<ApplicationTypeEntity> selectByExample(ApplicationTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    ApplicationTypeEntity selectByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") ApplicationTypeEntity record, @Param("example") ApplicationTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") ApplicationTypeEntity record, @Param("example") ApplicationTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(ApplicationTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(ApplicationTypeEntity record);
}