package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.ApplicationOrderEntity;
import com.chinasofti.rcloud.domain.ApplicationOrderEntityExample;
import com.chinasofti.rcloud.domain.ApplicationOrderEntityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplicationOrderEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(ApplicationOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(ApplicationOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(ApplicationOrderEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(ApplicationOrderEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<ApplicationOrderEntityWithBLOBs> selectByExampleWithBLOBs(ApplicationOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<ApplicationOrderEntity> selectByExample(ApplicationOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    ApplicationOrderEntityWithBLOBs selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") ApplicationOrderEntityWithBLOBs record, @Param("example") ApplicationOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ApplicationOrderEntityWithBLOBs record, @Param("example") ApplicationOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") ApplicationOrderEntity record, @Param("example") ApplicationOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(ApplicationOrderEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ApplicationOrderEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(ApplicationOrderEntity record);
}