package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.AuditLogEntity;
import com.chinasofti.rcloud.domain.AuditLogEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuditLogEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(AuditLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(AuditLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String auditLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(AuditLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(AuditLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<AuditLogEntity> selectByExample(AuditLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    AuditLogEntity selectByPrimaryKey(String auditLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") AuditLogEntity record, @Param("example") AuditLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") AuditLogEntity record, @Param("example") AuditLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(AuditLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(AuditLogEntity record);
}