package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.BillingMonthDetailEntity;
import com.chinasofti.rcloud.domain.BillingMonthDetailEntityExample;
import com.chinasofti.rcloud.domain.BillingMonthDetailEntityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillingMonthDetailEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(BillingMonthDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(BillingMonthDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(BillingMonthDetailEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(BillingMonthDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(BillingMonthDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<BillingMonthDetailEntity> selectByExample(BillingMonthDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    BillingMonthDetailEntity selectByPrimaryKey(BillingMonthDetailEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillingMonthDetailEntity record, @Param("example") BillingMonthDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") BillingMonthDetailEntity record, @Param("example") BillingMonthDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(BillingMonthDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month_detail
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(BillingMonthDetailEntity record);
}