package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.BillingMonthEntity;
import com.chinasofti.rcloud.domain.BillingMonthEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillingMonthEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(BillingMonthEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(BillingMonthEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String billingMonthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(BillingMonthEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(BillingMonthEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<BillingMonthEntity> selectByExample(BillingMonthEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    BillingMonthEntity selectByPrimaryKey(String billingMonthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillingMonthEntity record, @Param("example") BillingMonthEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") BillingMonthEntity record, @Param("example") BillingMonthEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(BillingMonthEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_billing_month
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(BillingMonthEntity record);
}