package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.BossDebtsRecordEntity;
import com.chinasofti.rcloud.domain.BossDebtsRecordEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BossDebtsRecordEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(BossDebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(BossDebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String debtsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(BossDebtsRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(BossDebtsRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<BossDebtsRecordEntity> selectByExample(BossDebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    BossDebtsRecordEntity selectByPrimaryKey(String debtsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") BossDebtsRecordEntity record, @Param("example") BossDebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") BossDebtsRecordEntity record, @Param("example") BossDebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(BossDebtsRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(BossDebtsRecordEntity record);
}