package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.BossServiceBillEntity;
import com.chinasofti.rcloud.domain.BossServiceBillEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BossServiceBillEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(BossServiceBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(BossServiceBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String serviceBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(BossServiceBillEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(BossServiceBillEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<BossServiceBillEntity> selectByExample(BossServiceBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    BossServiceBillEntity selectByPrimaryKey(String serviceBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") BossServiceBillEntity record, @Param("example") BossServiceBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") BossServiceBillEntity record, @Param("example") BossServiceBillEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(BossServiceBillEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_service_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(BossServiceBillEntity record);
}