package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.BusinessOrderEntity;
import com.chinasofti.rcloud.domain.BusinessOrderEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessOrderEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(BusinessOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(BusinessOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String businessOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(BusinessOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(BusinessOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<BusinessOrderEntity> selectByExampleWithBLOBs(BusinessOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<BusinessOrderEntity> selectByExample(BusinessOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    BusinessOrderEntity selectByPrimaryKey(String businessOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") BusinessOrderEntity record, @Param("example") BusinessOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") BusinessOrderEntity record, @Param("example") BusinessOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") BusinessOrderEntity record, @Param("example") BusinessOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(BusinessOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(BusinessOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_business_order
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(BusinessOrderEntity record);
}