package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.CurveSegmentsEntity;
import com.chinasofti.rcloud.domain.CurveSegmentsEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurveSegmentsEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(CurveSegmentsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(CurveSegmentsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String segmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(CurveSegmentsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(CurveSegmentsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<CurveSegmentsEntity> selectByExample(CurveSegmentsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    CurveSegmentsEntity selectByPrimaryKey(String segmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") CurveSegmentsEntity record, @Param("example") CurveSegmentsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") CurveSegmentsEntity record, @Param("example") CurveSegmentsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(CurveSegmentsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_curve_segments
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(CurveSegmentsEntity record);
}