package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.DebtsRecordEntity;
import com.chinasofti.rcloud.domain.DebtsRecordEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DebtsRecordEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(DebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(DebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String debtsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(DebtsRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(DebtsRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<DebtsRecordEntity> selectByExample(DebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    DebtsRecordEntity selectByPrimaryKey(String debtsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") DebtsRecordEntity record, @Param("example") DebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") DebtsRecordEntity record, @Param("example") DebtsRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(DebtsRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(DebtsRecordEntity record);
}