package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.OrganizationEntity;
import com.chinasofti.rcloud.domain.OrganizationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(OrganizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(OrganizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(OrganizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(OrganizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<OrganizationEntity> selectByExampleWithBLOBs(OrganizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<OrganizationEntity> selectByExample(OrganizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    OrganizationEntity selectByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrganizationEntity record, @Param("example") OrganizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") OrganizationEntity record, @Param("example") OrganizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") OrganizationEntity record, @Param("example") OrganizationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(OrganizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(OrganizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_organization
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(OrganizationEntity record);
}