package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.PermissionToRoleEntityExample;
import com.chinasofti.rcloud.domain.PermissionToRoleEntityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionToRoleEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(PermissionToRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(PermissionToRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(PermissionToRoleEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(PermissionToRoleEntityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(PermissionToRoleEntityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<PermissionToRoleEntityKey> selectByExample(PermissionToRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") PermissionToRoleEntityKey record, @Param("example") PermissionToRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") PermissionToRoleEntityKey record, @Param("example") PermissionToRoleEntityExample example);
}