package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.PkgEntity;
import com.chinasofti.rcloud.domain.PkgEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PkgEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(PkgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(PkgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String pkgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(PkgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(PkgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<PkgEntity> selectByExample(PkgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    PkgEntity selectByPrimaryKey(String pkgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") PkgEntity record, @Param("example") PkgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") PkgEntity record, @Param("example") PkgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(PkgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(PkgEntity record);
}