package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.PkgInstanceEntity;
import com.chinasofti.rcloud.domain.PkgInstanceEntityExample;
import com.chinasofti.rcloud.domain.PkgInstanceEntityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PkgInstanceEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(PkgInstanceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(PkgInstanceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(PkgInstanceEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(PkgInstanceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(PkgInstanceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<PkgInstanceEntity> selectByExample(PkgInstanceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    PkgInstanceEntity selectByPrimaryKey(PkgInstanceEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") PkgInstanceEntity record, @Param("example") PkgInstanceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") PkgInstanceEntity record, @Param("example") PkgInstanceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(PkgInstanceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(PkgInstanceEntity record);
}