package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.RatesEntity;
import com.chinasofti.rcloud.domain.RatesEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RatesEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(RatesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(RatesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String rateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(RatesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(RatesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<RatesEntity> selectByExample(RatesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    RatesEntity selectByPrimaryKey(String rateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") RatesEntity record, @Param("example") RatesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") RatesEntity record, @Param("example") RatesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(RatesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_rates
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(RatesEntity record);
}