package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.RoleEntity;
import com.chinasofti.rcloud.domain.RoleEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<RoleEntity> selectByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    RoleEntity selectByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(RoleEntity record);
}