package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.SpaceEntity;
import com.chinasofti.rcloud.domain.SpaceEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpaceEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String spaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(SpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(SpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<SpaceEntity> selectByExampleWithBLOBs(SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<SpaceEntity> selectByExample(SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    SpaceEntity selectByPrimaryKey(String spaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") SpaceEntity record, @Param("example") SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") SpaceEntity record, @Param("example") SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") SpaceEntity record, @Param("example") SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(SpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(SpaceEntity record);
}