package com.chinasofti.rcloud.dao;

import com.chinasofti.rcloud.common.dao.BaseDao;
import com.chinasofti.rcloud.domain.UserAccountEntity;
import com.chinasofti.rcloud.domain.UserAccountEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountEntityMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int countByExample(UserAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByExample(UserAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insert(UserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int insertSelective(UserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    List<UserAccountEntity> selectByExample(UserAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    UserAccountEntity selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserAccountEntity record, @Param("example") UserAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByExample(@Param("record") UserAccountEntity record, @Param("example") UserAccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKeySelective(UserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_user_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    int updateByPrimaryKey(UserAccountEntity record);
}