package com.chinasofti.rcloud.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccessKeyRecordEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public AccessKeyRecordEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccessKeyIdIsNull() {
            addCriterion("access_key_id is null");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdIsNotNull() {
            addCriterion("access_key_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdEqualTo(String value) {
            addCriterion("access_key_id =", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdNotEqualTo(String value) {
            addCriterion("access_key_id <>", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdGreaterThan(String value) {
            addCriterion("access_key_id >", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdGreaterThanOrEqualTo(String value) {
            addCriterion("access_key_id >=", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdLessThan(String value) {
            addCriterion("access_key_id <", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdLessThanOrEqualTo(String value) {
            addCriterion("access_key_id <=", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdLike(String value) {
            addCriterion("access_key_id like", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdNotLike(String value) {
            addCriterion("access_key_id not like", value, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdIn(List<String> values) {
            addCriterion("access_key_id in", values, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdNotIn(List<String> values) {
            addCriterion("access_key_id not in", values, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdBetween(String value1, String value2) {
            addCriterion("access_key_id between", value1, value2, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andAccessKeyIdNotBetween(String value1, String value2) {
            addCriterion("access_key_id not between", value1, value2, "accessKeyId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserGuidIsNull() {
            addCriterion("user_guid is null");
            return (Criteria) this;
        }

        public Criteria andUserGuidIsNotNull() {
            addCriterion("user_guid is not null");
            return (Criteria) this;
        }

        public Criteria andUserGuidEqualTo(String value) {
            addCriterion("user_guid =", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotEqualTo(String value) {
            addCriterion("user_guid <>", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidGreaterThan(String value) {
            addCriterion("user_guid >", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidGreaterThanOrEqualTo(String value) {
            addCriterion("user_guid >=", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidLessThan(String value) {
            addCriterion("user_guid <", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidLessThanOrEqualTo(String value) {
            addCriterion("user_guid <=", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidLike(String value) {
            addCriterion("user_guid like", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotLike(String value) {
            addCriterion("user_guid not like", value, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidIn(List<String> values) {
            addCriterion("user_guid in", values, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotIn(List<String> values) {
            addCriterion("user_guid not in", values, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidBetween(String value1, String value2) {
            addCriterion("user_guid between", value1, value2, "userGuid");
            return (Criteria) this;
        }

        public Criteria andUserGuidNotBetween(String value1, String value2) {
            addCriterion("user_guid not between", value1, value2, "userGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidIsNull() {
            addCriterion("org_guid is null");
            return (Criteria) this;
        }

        public Criteria andOrgGuidIsNotNull() {
            addCriterion("org_guid is not null");
            return (Criteria) this;
        }

        public Criteria andOrgGuidEqualTo(String value) {
            addCriterion("org_guid =", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidNotEqualTo(String value) {
            addCriterion("org_guid <>", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidGreaterThan(String value) {
            addCriterion("org_guid >", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidGreaterThanOrEqualTo(String value) {
            addCriterion("org_guid >=", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidLessThan(String value) {
            addCriterion("org_guid <", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidLessThanOrEqualTo(String value) {
            addCriterion("org_guid <=", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidLike(String value) {
            addCriterion("org_guid like", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidNotLike(String value) {
            addCriterion("org_guid not like", value, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidIn(List<String> values) {
            addCriterion("org_guid in", values, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidNotIn(List<String> values) {
            addCriterion("org_guid not in", values, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidBetween(String value1, String value2) {
            addCriterion("org_guid between", value1, value2, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andOrgGuidNotBetween(String value1, String value2) {
            addCriterion("org_guid not between", value1, value2, "orgGuid");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretIsNull() {
            addCriterion("access_key_secret is null");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretIsNotNull() {
            addCriterion("access_key_secret is not null");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretEqualTo(String value) {
            addCriterion("access_key_secret =", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretNotEqualTo(String value) {
            addCriterion("access_key_secret <>", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretGreaterThan(String value) {
            addCriterion("access_key_secret >", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretGreaterThanOrEqualTo(String value) {
            addCriterion("access_key_secret >=", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretLessThan(String value) {
            addCriterion("access_key_secret <", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretLessThanOrEqualTo(String value) {
            addCriterion("access_key_secret <=", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretLike(String value) {
            addCriterion("access_key_secret like", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretNotLike(String value) {
            addCriterion("access_key_secret not like", value, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretIn(List<String> values) {
            addCriterion("access_key_secret in", values, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretNotIn(List<String> values) {
            addCriterion("access_key_secret not in", values, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretBetween(String value1, String value2) {
            addCriterion("access_key_secret between", value1, value2, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andAccessKeySecretNotBetween(String value1, String value2) {
            addCriterion("access_key_secret not between", value1, value2, "accessKeySecret");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeIsNull() {
            addCriterion("active_time is null");
            return (Criteria) this;
        }

        public Criteria andActiveTimeIsNotNull() {
            addCriterion("active_time is not null");
            return (Criteria) this;
        }

        public Criteria andActiveTimeEqualTo(Date value) {
            addCriterion("active_time =", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeNotEqualTo(Date value) {
            addCriterion("active_time <>", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeGreaterThan(Date value) {
            addCriterion("active_time >", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("active_time >=", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeLessThan(Date value) {
            addCriterion("active_time <", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("active_time <=", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeIn(List<Date> values) {
            addCriterion("active_time in", values, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeNotIn(List<Date> values) {
            addCriterion("active_time not in", values, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeBetween(Date value1, Date value2) {
            addCriterion("active_time between", value1, value2, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("active_time not between", value1, value2, "activeTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_access_key_record
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 19 10:09:58 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}