package com.chinasofti.rcloud.domain;

import java.io.Serializable;
import java.util.Date;

public class AccessKeyRecordEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.access_key_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String accessKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.user_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String orgGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.access_key_secret
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String accessKeySecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.created_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_access_key_record.active_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date activeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_access_key_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.access_key_id
     *
     * @return the value of portal_access_key_record.access_key_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getAccessKeyId() {
        return accessKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.access_key_id
     *
     * @param accessKeyId the value for portal_access_key_record.access_key_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setAccessKeyId(String accessKeyId) {
        this.accessKeyId = accessKeyId == null ? null : accessKeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.user_id
     *
     * @return the value of portal_access_key_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.user_id
     *
     * @param userId the value for portal_access_key_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.user_guid
     *
     * @return the value of portal_access_key_record.user_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserGuid() {
        return userGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.user_guid
     *
     * @param userGuid the value for portal_access_key_record.user_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserGuid(String userGuid) {
        this.userGuid = userGuid == null ? null : userGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.org_guid
     *
     * @return the value of portal_access_key_record.org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getOrgGuid() {
        return orgGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.org_guid
     *
     * @param orgGuid the value for portal_access_key_record.org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOrgGuid(String orgGuid) {
        this.orgGuid = orgGuid == null ? null : orgGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.access_key_secret
     *
     * @return the value of portal_access_key_record.access_key_secret
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getAccessKeySecret() {
        return accessKeySecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.access_key_secret
     *
     * @param accessKeySecret the value for portal_access_key_record.access_key_secret
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setAccessKeySecret(String accessKeySecret) {
        this.accessKeySecret = accessKeySecret == null ? null : accessKeySecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.status
     *
     * @return the value of portal_access_key_record.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.status
     *
     * @param status the value for portal_access_key_record.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.created_time
     *
     * @return the value of portal_access_key_record.created_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.created_time
     *
     * @param createdTime the value for portal_access_key_record.created_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_access_key_record.active_time
     *
     * @return the value of portal_access_key_record.active_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_access_key_record.active_time
     *
     * @param activeTime the value for portal_access_key_record.active_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }
}