package com.chinasofti.rcloud.domain;

import java.io.Serializable;
import java.util.Date;

public class AccountingCycleRecordEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_accounting_cycle_record.id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_accounting_cycle_record.ori_accounting_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer oriAccountingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_accounting_cycle_record.cur_accounting_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer curAccountingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_accounting_cycle_record.mark_accounting
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer markAccounting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_accounting_cycle_record.modify_user
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_accounting_cycle_record.modify_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_accounting_cycle_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_accounting_cycle_record.id
     *
     * @return the value of boss_accounting_cycle_record.id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_accounting_cycle_record.id
     *
     * @param id the value for boss_accounting_cycle_record.id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_accounting_cycle_record.ori_accounting_time
     *
     * @return the value of boss_accounting_cycle_record.ori_accounting_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getOriAccountingTime() {
        return oriAccountingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_accounting_cycle_record.ori_accounting_time
     *
     * @param oriAccountingTime the value for boss_accounting_cycle_record.ori_accounting_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOriAccountingTime(Integer oriAccountingTime) {
        this.oriAccountingTime = oriAccountingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_accounting_cycle_record.cur_accounting_time
     *
     * @return the value of boss_accounting_cycle_record.cur_accounting_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getCurAccountingTime() {
        return curAccountingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_accounting_cycle_record.cur_accounting_time
     *
     * @param curAccountingTime the value for boss_accounting_cycle_record.cur_accounting_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCurAccountingTime(Integer curAccountingTime) {
        this.curAccountingTime = curAccountingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_accounting_cycle_record.mark_accounting
     *
     * @return the value of boss_accounting_cycle_record.mark_accounting
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getMarkAccounting() {
        return markAccounting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_accounting_cycle_record.mark_accounting
     *
     * @param markAccounting the value for boss_accounting_cycle_record.mark_accounting
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setMarkAccounting(Integer markAccounting) {
        this.markAccounting = markAccounting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_accounting_cycle_record.modify_user
     *
     * @return the value of boss_accounting_cycle_record.modify_user
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_accounting_cycle_record.modify_user
     *
     * @param modifyUser the value for boss_accounting_cycle_record.modify_user
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_accounting_cycle_record.modify_time
     *
     * @return the value of boss_accounting_cycle_record.modify_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_accounting_cycle_record.modify_time
     *
     * @param modifyTime the value for boss_accounting_cycle_record.modify_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}