package com.chinasofti.rcloud.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApplicationEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public ApplicationEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApplicationIdIsNull() {
            addCriterion("application_id is null");
            return (Criteria) this;
        }

        public Criteria andApplicationIdIsNotNull() {
            addCriterion("application_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationIdEqualTo(String value) {
            addCriterion("application_id =", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotEqualTo(String value) {
            addCriterion("application_id <>", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdGreaterThan(String value) {
            addCriterion("application_id >", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdGreaterThanOrEqualTo(String value) {
            addCriterion("application_id >=", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdLessThan(String value) {
            addCriterion("application_id <", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdLessThanOrEqualTo(String value) {
            addCriterion("application_id <=", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdLike(String value) {
            addCriterion("application_id like", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotLike(String value) {
            addCriterion("application_id not like", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdIn(List<String> values) {
            addCriterion("application_id in", values, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotIn(List<String> values) {
            addCriterion("application_id not in", values, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdBetween(String value1, String value2) {
            addCriterion("application_id between", value1, value2, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotBetween(String value1, String value2) {
            addCriterion("application_id not between", value1, value2, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNull() {
            addCriterion("application_name is null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNotNull() {
            addCriterion("application_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameEqualTo(String value) {
            addCriterion("application_name =", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotEqualTo(String value) {
            addCriterion("application_name <>", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThan(String value) {
            addCriterion("application_name >", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThanOrEqualTo(String value) {
            addCriterion("application_name >=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThan(String value) {
            addCriterion("application_name <", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThanOrEqualTo(String value) {
            addCriterion("application_name <=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLike(String value) {
            addCriterion("application_name like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotLike(String value) {
            addCriterion("application_name not like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIn(List<String> values) {
            addCriterion("application_name in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotIn(List<String> values) {
            addCriterion("application_name not in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameBetween(String value1, String value2) {
            addCriterion("application_name between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotBetween(String value1, String value2) {
            addCriterion("application_name not between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeIsNull() {
            addCriterion("shelve_time is null");
            return (Criteria) this;
        }

        public Criteria andShelveTimeIsNotNull() {
            addCriterion("shelve_time is not null");
            return (Criteria) this;
        }

        public Criteria andShelveTimeEqualTo(Date value) {
            addCriterion("shelve_time =", value, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeNotEqualTo(Date value) {
            addCriterion("shelve_time <>", value, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeGreaterThan(Date value) {
            addCriterion("shelve_time >", value, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shelve_time >=", value, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeLessThan(Date value) {
            addCriterion("shelve_time <", value, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeLessThanOrEqualTo(Date value) {
            addCriterion("shelve_time <=", value, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeIn(List<Date> values) {
            addCriterion("shelve_time in", values, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeNotIn(List<Date> values) {
            addCriterion("shelve_time not in", values, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeBetween(Date value1, Date value2) {
            addCriterion("shelve_time between", value1, value2, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andShelveTimeNotBetween(Date value1, Date value2) {
            addCriterion("shelve_time not between", value1, value2, "shelveTime");
            return (Criteria) this;
        }

        public Criteria andLogoPathIsNull() {
            addCriterion("logo_path is null");
            return (Criteria) this;
        }

        public Criteria andLogoPathIsNotNull() {
            addCriterion("logo_path is not null");
            return (Criteria) this;
        }

        public Criteria andLogoPathEqualTo(String value) {
            addCriterion("logo_path =", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathNotEqualTo(String value) {
            addCriterion("logo_path <>", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathGreaterThan(String value) {
            addCriterion("logo_path >", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathGreaterThanOrEqualTo(String value) {
            addCriterion("logo_path >=", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathLessThan(String value) {
            addCriterion("logo_path <", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathLessThanOrEqualTo(String value) {
            addCriterion("logo_path <=", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathLike(String value) {
            addCriterion("logo_path like", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathNotLike(String value) {
            addCriterion("logo_path not like", value, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathIn(List<String> values) {
            addCriterion("logo_path in", values, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathNotIn(List<String> values) {
            addCriterion("logo_path not in", values, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathBetween(String value1, String value2) {
            addCriterion("logo_path between", value1, value2, "logoPath");
            return (Criteria) this;
        }

        public Criteria andLogoPathNotBetween(String value1, String value2) {
            addCriterion("logo_path not between", value1, value2, "logoPath");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andProviderIdIsNull() {
            addCriterion("provider_id is null");
            return (Criteria) this;
        }

        public Criteria andProviderIdIsNotNull() {
            addCriterion("provider_id is not null");
            return (Criteria) this;
        }

        public Criteria andProviderIdEqualTo(String value) {
            addCriterion("provider_id =", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdNotEqualTo(String value) {
            addCriterion("provider_id <>", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdGreaterThan(String value) {
            addCriterion("provider_id >", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdGreaterThanOrEqualTo(String value) {
            addCriterion("provider_id >=", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdLessThan(String value) {
            addCriterion("provider_id <", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdLessThanOrEqualTo(String value) {
            addCriterion("provider_id <=", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdLike(String value) {
            addCriterion("provider_id like", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdNotLike(String value) {
            addCriterion("provider_id not like", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdIn(List<String> values) {
            addCriterion("provider_id in", values, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdNotIn(List<String> values) {
            addCriterion("provider_id not in", values, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdBetween(String value1, String value2) {
            addCriterion("provider_id between", value1, value2, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdNotBetween(String value1, String value2) {
            addCriterion("provider_id not between", value1, value2, "providerId");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteIsNull() {
            addCriterion("mark_delete is null");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteIsNotNull() {
            addCriterion("mark_delete is not null");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteEqualTo(Integer value) {
            addCriterion("mark_delete =", value, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteNotEqualTo(Integer value) {
            addCriterion("mark_delete <>", value, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteGreaterThan(Integer value) {
            addCriterion("mark_delete >", value, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("mark_delete >=", value, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteLessThan(Integer value) {
            addCriterion("mark_delete <", value, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("mark_delete <=", value, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteIn(List<Integer> values) {
            addCriterion("mark_delete in", values, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteNotIn(List<Integer> values) {
            addCriterion("mark_delete not in", values, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteBetween(Integer value1, Integer value2) {
            addCriterion("mark_delete between", value1, value2, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMarkDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("mark_delete not between", value1, value2, "markDelete");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsIsNull() {
            addCriterion("maintenance_costs is null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsIsNotNull() {
            addCriterion("maintenance_costs is not null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsEqualTo(BigDecimal value) {
            addCriterion("maintenance_costs =", value, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsNotEqualTo(BigDecimal value) {
            addCriterion("maintenance_costs <>", value, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsGreaterThan(BigDecimal value) {
            addCriterion("maintenance_costs >", value, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("maintenance_costs >=", value, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsLessThan(BigDecimal value) {
            addCriterion("maintenance_costs <", value, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("maintenance_costs <=", value, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsIn(List<BigDecimal> values) {
            addCriterion("maintenance_costs in", values, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsNotIn(List<BigDecimal> values) {
            addCriterion("maintenance_costs not in", values, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("maintenance_costs between", value1, value2, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andMaintenanceCostsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("maintenance_costs not between", value1, value2, "maintenanceCosts");
            return (Criteria) this;
        }

        public Criteria andSubDomainIsNull() {
            addCriterion("sub_domain is null");
            return (Criteria) this;
        }

        public Criteria andSubDomainIsNotNull() {
            addCriterion("sub_domain is not null");
            return (Criteria) this;
        }

        public Criteria andSubDomainEqualTo(String value) {
            addCriterion("sub_domain =", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainNotEqualTo(String value) {
            addCriterion("sub_domain <>", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainGreaterThan(String value) {
            addCriterion("sub_domain >", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainGreaterThanOrEqualTo(String value) {
            addCriterion("sub_domain >=", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainLessThan(String value) {
            addCriterion("sub_domain <", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainLessThanOrEqualTo(String value) {
            addCriterion("sub_domain <=", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainLike(String value) {
            addCriterion("sub_domain like", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainNotLike(String value) {
            addCriterion("sub_domain not like", value, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainIn(List<String> values) {
            addCriterion("sub_domain in", values, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainNotIn(List<String> values) {
            addCriterion("sub_domain not in", values, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainBetween(String value1, String value2) {
            addCriterion("sub_domain between", value1, value2, "subDomain");
            return (Criteria) this;
        }

        public Criteria andSubDomainNotBetween(String value1, String value2) {
            addCriterion("sub_domain not between", value1, value2, "subDomain");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeIsNull() {
            addCriterion("application_type is null");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeIsNotNull() {
            addCriterion("application_type is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeEqualTo(String value) {
            addCriterion("application_type =", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotEqualTo(String value) {
            addCriterion("application_type <>", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeGreaterThan(String value) {
            addCriterion("application_type >", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("application_type >=", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeLessThan(String value) {
            addCriterion("application_type <", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeLessThanOrEqualTo(String value) {
            addCriterion("application_type <=", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeLike(String value) {
            addCriterion("application_type like", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotLike(String value) {
            addCriterion("application_type not like", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeIn(List<String> values) {
            addCriterion("application_type in", values, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotIn(List<String> values) {
            addCriterion("application_type not in", values, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeBetween(String value1, String value2) {
            addCriterion("application_type between", value1, value2, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotBetween(String value1, String value2) {
            addCriterion("application_type not between", value1, value2, "applicationType");
            return (Criteria) this;
        }

        public Criteria andBaseAppIsNull() {
            addCriterion("base_app is null");
            return (Criteria) this;
        }

        public Criteria andBaseAppIsNotNull() {
            addCriterion("base_app is not null");
            return (Criteria) this;
        }

        public Criteria andBaseAppEqualTo(String value) {
            addCriterion("base_app =", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppNotEqualTo(String value) {
            addCriterion("base_app <>", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppGreaterThan(String value) {
            addCriterion("base_app >", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppGreaterThanOrEqualTo(String value) {
            addCriterion("base_app >=", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppLessThan(String value) {
            addCriterion("base_app <", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppLessThanOrEqualTo(String value) {
            addCriterion("base_app <=", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppLike(String value) {
            addCriterion("base_app like", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppNotLike(String value) {
            addCriterion("base_app not like", value, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppIn(List<String> values) {
            addCriterion("base_app in", values, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppNotIn(List<String> values) {
            addCriterion("base_app not in", values, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppBetween(String value1, String value2) {
            addCriterion("base_app between", value1, value2, "baseApp");
            return (Criteria) this;
        }

        public Criteria andBaseAppNotBetween(String value1, String value2) {
            addCriterion("base_app not between", value1, value2, "baseApp");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNull() {
            addCriterion("app_version is null");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNotNull() {
            addCriterion("app_version is not null");
            return (Criteria) this;
        }

        public Criteria andAppVersionEqualTo(String value) {
            addCriterion("app_version =", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotEqualTo(String value) {
            addCriterion("app_version <>", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThan(String value) {
            addCriterion("app_version >", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThanOrEqualTo(String value) {
            addCriterion("app_version >=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThan(String value) {
            addCriterion("app_version <", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThanOrEqualTo(String value) {
            addCriterion("app_version <=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLike(String value) {
            addCriterion("app_version like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotLike(String value) {
            addCriterion("app_version not like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionIn(List<String> values) {
            addCriterion("app_version in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotIn(List<String> values) {
            addCriterion("app_version not in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionBetween(String value1, String value2) {
            addCriterion("app_version between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotBetween(String value1, String value2) {
            addCriterion("app_version not between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNull() {
            addCriterion("contact_person is null");
            return (Criteria) this;
        }

        public Criteria andContactPersonIsNotNull() {
            addCriterion("contact_person is not null");
            return (Criteria) this;
        }

        public Criteria andContactPersonEqualTo(String value) {
            addCriterion("contact_person =", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotEqualTo(String value) {
            addCriterion("contact_person <>", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThan(String value) {
            addCriterion("contact_person >", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("contact_person >=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThan(String value) {
            addCriterion("contact_person <", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLessThanOrEqualTo(String value) {
            addCriterion("contact_person <=", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonLike(String value) {
            addCriterion("contact_person like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotLike(String value) {
            addCriterion("contact_person not like", value, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonIn(List<String> values) {
            addCriterion("contact_person in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotIn(List<String> values) {
            addCriterion("contact_person not in", values, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonBetween(String value1, String value2) {
            addCriterion("contact_person between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPersonNotBetween(String value1, String value2) {
            addCriterion("contact_person not between", value1, value2, "contactPerson");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNull() {
            addCriterion("contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNotNull() {
            addCriterion("contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneEqualTo(String value) {
            addCriterion("contact_phone =", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotEqualTo(String value) {
            addCriterion("contact_phone <>", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThan(String value) {
            addCriterion("contact_phone >", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contact_phone >=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThan(String value) {
            addCriterion("contact_phone <", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("contact_phone <=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLike(String value) {
            addCriterion("contact_phone like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotLike(String value) {
            addCriterion("contact_phone not like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIn(List<String> values) {
            addCriterion("contact_phone in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotIn(List<String> values) {
            addCriterion("contact_phone not in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneBetween(String value1, String value2) {
            addCriterion("contact_phone between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotBetween(String value1, String value2) {
            addCriterion("contact_phone not between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andShowPortalIsNull() {
            addCriterion("show_portal is null");
            return (Criteria) this;
        }

        public Criteria andShowPortalIsNotNull() {
            addCriterion("show_portal is not null");
            return (Criteria) this;
        }

        public Criteria andShowPortalEqualTo(Integer value) {
            addCriterion("show_portal =", value, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalNotEqualTo(Integer value) {
            addCriterion("show_portal <>", value, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalGreaterThan(Integer value) {
            addCriterion("show_portal >", value, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_portal >=", value, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalLessThan(Integer value) {
            addCriterion("show_portal <", value, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalLessThanOrEqualTo(Integer value) {
            addCriterion("show_portal <=", value, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalIn(List<Integer> values) {
            addCriterion("show_portal in", values, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalNotIn(List<Integer> values) {
            addCriterion("show_portal not in", values, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalBetween(Integer value1, Integer value2) {
            addCriterion("show_portal between", value1, value2, "showPortal");
            return (Criteria) this;
        }

        public Criteria andShowPortalNotBetween(Integer value1, Integer value2) {
            addCriterion("show_portal not between", value1, value2, "showPortal");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverIsNull() {
            addCriterion("logo_path_hover is null");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverIsNotNull() {
            addCriterion("logo_path_hover is not null");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverEqualTo(String value) {
            addCriterion("logo_path_hover =", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverNotEqualTo(String value) {
            addCriterion("logo_path_hover <>", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverGreaterThan(String value) {
            addCriterion("logo_path_hover >", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverGreaterThanOrEqualTo(String value) {
            addCriterion("logo_path_hover >=", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverLessThan(String value) {
            addCriterion("logo_path_hover <", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverLessThanOrEqualTo(String value) {
            addCriterion("logo_path_hover <=", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverLike(String value) {
            addCriterion("logo_path_hover like", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverNotLike(String value) {
            addCriterion("logo_path_hover not like", value, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverIn(List<String> values) {
            addCriterion("logo_path_hover in", values, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverNotIn(List<String> values) {
            addCriterion("logo_path_hover not in", values, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverBetween(String value1, String value2) {
            addCriterion("logo_path_hover between", value1, value2, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andLogoPathHoverNotBetween(String value1, String value2) {
            addCriterion("logo_path_hover not between", value1, value2, "logoPathHover");
            return (Criteria) this;
        }

        public Criteria andChnameIsNull() {
            addCriterion("chname is null");
            return (Criteria) this;
        }

        public Criteria andChnameIsNotNull() {
            addCriterion("chname is not null");
            return (Criteria) this;
        }

        public Criteria andChnameEqualTo(String value) {
            addCriterion("chname =", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotEqualTo(String value) {
            addCriterion("chname <>", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameGreaterThan(String value) {
            addCriterion("chname >", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameGreaterThanOrEqualTo(String value) {
            addCriterion("chname >=", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameLessThan(String value) {
            addCriterion("chname <", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameLessThanOrEqualTo(String value) {
            addCriterion("chname <=", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameLike(String value) {
            addCriterion("chname like", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotLike(String value) {
            addCriterion("chname not like", value, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameIn(List<String> values) {
            addCriterion("chname in", values, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotIn(List<String> values) {
            addCriterion("chname not in", values, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameBetween(String value1, String value2) {
            addCriterion("chname between", value1, value2, "chname");
            return (Criteria) this;
        }

        public Criteria andChnameNotBetween(String value1, String value2) {
            addCriterion("chname not between", value1, value2, "chname");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlIsNull() {
            addCriterion("show_detail_url is null");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlIsNotNull() {
            addCriterion("show_detail_url is not null");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlEqualTo(String value) {
            addCriterion("show_detail_url =", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlNotEqualTo(String value) {
            addCriterion("show_detail_url <>", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlGreaterThan(String value) {
            addCriterion("show_detail_url >", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlGreaterThanOrEqualTo(String value) {
            addCriterion("show_detail_url >=", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlLessThan(String value) {
            addCriterion("show_detail_url <", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlLessThanOrEqualTo(String value) {
            addCriterion("show_detail_url <=", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlLike(String value) {
            addCriterion("show_detail_url like", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlNotLike(String value) {
            addCriterion("show_detail_url not like", value, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlIn(List<String> values) {
            addCriterion("show_detail_url in", values, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlNotIn(List<String> values) {
            addCriterion("show_detail_url not in", values, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlBetween(String value1, String value2) {
            addCriterion("show_detail_url between", value1, value2, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andShowDetailUrlNotBetween(String value1, String value2) {
            addCriterion("show_detail_url not between", value1, value2, "showDetailUrl");
            return (Criteria) this;
        }

        public Criteria andDeployTypeIsNull() {
            addCriterion("deploy_type is null");
            return (Criteria) this;
        }

        public Criteria andDeployTypeIsNotNull() {
            addCriterion("deploy_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeployTypeEqualTo(Integer value) {
            addCriterion("deploy_type =", value, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeNotEqualTo(Integer value) {
            addCriterion("deploy_type <>", value, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeGreaterThan(Integer value) {
            addCriterion("deploy_type >", value, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("deploy_type >=", value, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeLessThan(Integer value) {
            addCriterion("deploy_type <", value, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeLessThanOrEqualTo(Integer value) {
            addCriterion("deploy_type <=", value, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeIn(List<Integer> values) {
            addCriterion("deploy_type in", values, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeNotIn(List<Integer> values) {
            addCriterion("deploy_type not in", values, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeBetween(Integer value1, Integer value2) {
            addCriterion("deploy_type between", value1, value2, "deployType");
            return (Criteria) this;
        }

        public Criteria andDeployTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("deploy_type not between", value1, value2, "deployType");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadIsNull() {
            addCriterion("allowDownload is null");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadIsNotNull() {
            addCriterion("allowDownload is not null");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadEqualTo(Integer value) {
            addCriterion("allowDownload =", value, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadNotEqualTo(Integer value) {
            addCriterion("allowDownload <>", value, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadGreaterThan(Integer value) {
            addCriterion("allowDownload >", value, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadGreaterThanOrEqualTo(Integer value) {
            addCriterion("allowDownload >=", value, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadLessThan(Integer value) {
            addCriterion("allowDownload <", value, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadLessThanOrEqualTo(Integer value) {
            addCriterion("allowDownload <=", value, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadIn(List<Integer> values) {
            addCriterion("allowDownload in", values, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadNotIn(List<Integer> values) {
            addCriterion("allowDownload not in", values, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadBetween(Integer value1, Integer value2) {
            addCriterion("allowDownload between", value1, value2, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andAllowdownloadNotBetween(Integer value1, Integer value2) {
            addCriterion("allowDownload not between", value1, value2, "allowdownload");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionIsNull() {
            addCriterion("off_shelve_description is null");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionIsNotNull() {
            addCriterion("off_shelve_description is not null");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionEqualTo(String value) {
            addCriterion("off_shelve_description =", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionNotEqualTo(String value) {
            addCriterion("off_shelve_description <>", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionGreaterThan(String value) {
            addCriterion("off_shelve_description >", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("off_shelve_description >=", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionLessThan(String value) {
            addCriterion("off_shelve_description <", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionLessThanOrEqualTo(String value) {
            addCriterion("off_shelve_description <=", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionLike(String value) {
            addCriterion("off_shelve_description like", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionNotLike(String value) {
            addCriterion("off_shelve_description not like", value, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionIn(List<String> values) {
            addCriterion("off_shelve_description in", values, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionNotIn(List<String> values) {
            addCriterion("off_shelve_description not in", values, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionBetween(String value1, String value2) {
            addCriterion("off_shelve_description between", value1, value2, "offShelveDescription");
            return (Criteria) this;
        }

        public Criteria andOffShelveDescriptionNotBetween(String value1, String value2) {
            addCriterion("off_shelve_description not between", value1, value2, "offShelveDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_application
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 19 10:09:58 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}