package com.chinasofti.rcloud.domain;

import java.io.Serializable;

public class ApplicationTypeEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_application_type.type_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_application_type.type_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_application_type.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer markDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_application_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_application_type.type_id
     *
     * @return the value of boss_application_type.type_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_application_type.type_id
     *
     * @param typeId the value for boss_application_type.type_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_application_type.type_name
     *
     * @return the value of boss_application_type.type_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_application_type.type_name
     *
     * @param typeName the value for boss_application_type.type_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_application_type.mark_delete
     *
     * @return the value of boss_application_type.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_application_type.mark_delete
     *
     * @param markDelete the value for boss_application_type.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }
}