package com.chinasofti.rcloud.domain;

import java.io.Serializable;

public class ApplicationOrderToBillEntityKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_application_order_to_bill.order_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_application_order_to_bill.bill_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_application_order_to_bill
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_application_order_to_bill.order_id
     *
     * @return the value of portal_application_order_to_bill.order_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_application_order_to_bill.order_id
     *
     * @param orderId the value for portal_application_order_to_bill.order_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_application_order_to_bill.bill_id
     *
     * @return the value of portal_application_order_to_bill.bill_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_application_order_to_bill.bill_id
     *
     * @param billId the value for portal_application_order_to_bill.bill_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setBillId(String billId) {
        this.billId = billId == null ? null : billId.trim();
    }
}