package com.chinasofti.rcloud.domain;

import java.io.Serializable;

public class ApplicationEntityWithBLOBs extends ApplicationEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_application.brief_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String briefDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_application.detail_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String detailDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_application
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_application.brief_description
     *
     * @return the value of portal_application.brief_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getBriefDescription() {
        return briefDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_application.brief_description
     *
     * @param briefDescription the value for portal_application.brief_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription == null ? null : briefDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_application.detail_description
     *
     * @return the value of portal_application.detail_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getDetailDescription() {
        return detailDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_application.detail_description
     *
     * @param detailDescription the value for portal_application.detail_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setDetailDescription(String detailDescription) {
        this.detailDescription = detailDescription == null ? null : detailDescription.trim();
    }
}