package com.chinasofti.rcloud.domain;

import java.io.Serializable;
import java.util.Date;

public class AuditLogEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.audit_log_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String auditLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.service_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.user_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.create_date
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.operation
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.remarks
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_audit_log.description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_audit_log
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.audit_log_id
     *
     * @return the value of boss_audit_log.audit_log_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getAuditLogId() {
        return auditLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.audit_log_id
     *
     * @param auditLogId the value for boss_audit_log.audit_log_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setAuditLogId(String auditLogId) {
        this.auditLogId = auditLogId == null ? null : auditLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.user_id
     *
     * @return the value of boss_audit_log.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.user_id
     *
     * @param userId the value for boss_audit_log.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.service_id
     *
     * @return the value of boss_audit_log.service_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.service_id
     *
     * @param serviceId the value for boss_audit_log.service_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.user_type
     *
     * @return the value of boss_audit_log.user_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.user_type
     *
     * @param userType the value for boss_audit_log.user_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.role_code
     *
     * @return the value of boss_audit_log.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.role_code
     *
     * @param roleCode the value for boss_audit_log.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.create_date
     *
     * @return the value of boss_audit_log.create_date
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.create_date
     *
     * @param createDate the value for boss_audit_log.create_date
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.operation
     *
     * @return the value of boss_audit_log.operation
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.operation
     *
     * @param operation the value for boss_audit_log.operation
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.remarks
     *
     * @return the value of boss_audit_log.remarks
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.remarks
     *
     * @param remarks the value for boss_audit_log.remarks
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_audit_log.description
     *
     * @return the value of boss_audit_log.description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_audit_log.description
     *
     * @param description the value for boss_audit_log.description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}