package com.chinasofti.rcloud.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DebtsRecordEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.debts_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String debtsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.bill_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.debts_costs
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private BigDecimal debtsCosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.created_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.payment_date
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_debts_record.type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_debts_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.debts_id
     *
     * @return the value of portal_debts_record.debts_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getDebtsId() {
        return debtsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.debts_id
     *
     * @param debtsId the value for portal_debts_record.debts_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setDebtsId(String debtsId) {
        this.debtsId = debtsId == null ? null : debtsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.bill_id
     *
     * @return the value of portal_debts_record.bill_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.bill_id
     *
     * @param billId the value for portal_debts_record.bill_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setBillId(String billId) {
        this.billId = billId == null ? null : billId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.debts_costs
     *
     * @return the value of portal_debts_record.debts_costs
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public BigDecimal getDebtsCosts() {
        return debtsCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.debts_costs
     *
     * @param debtsCosts the value for portal_debts_record.debts_costs
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setDebtsCosts(BigDecimal debtsCosts) {
        this.debtsCosts = debtsCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.created_time
     *
     * @return the value of portal_debts_record.created_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.created_time
     *
     * @param createdTime the value for portal_debts_record.created_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.status
     *
     * @return the value of portal_debts_record.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.status
     *
     * @param status the value for portal_debts_record.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.payment_date
     *
     * @return the value of portal_debts_record.payment_date
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.payment_date
     *
     * @param paymentDate the value for portal_debts_record.payment_date
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.user_id
     *
     * @return the value of portal_debts_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.user_id
     *
     * @param userId the value for portal_debts_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_debts_record.type
     *
     * @return the value of portal_debts_record.type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_debts_record.type
     *
     * @param type the value for portal_debts_record.type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }
}