package com.chinasofti.rcloud.domain;

import java.io.Serializable;

public class PermissionToRoleEntityKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_permission_to_role.permission_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String permissionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_permission_to_role.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_permission_to_role
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_permission_to_role.permission_code
     *
     * @return the value of portal_permission_to_role.permission_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_permission_to_role.permission_code
     *
     * @param permissionCode the value for portal_permission_to_role.permission_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_permission_to_role.role_code
     *
     * @return the value of portal_permission_to_role.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_permission_to_role.role_code
     *
     * @param roleCode the value for portal_permission_to_role.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }
}