package com.chinasofti.rcloud.domain;

import java.io.Serializable;

public class PkgInstanceEntity extends PkgInstanceEntityKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_pkg_instance.remarks
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_pkg_instance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_pkg_instance.remarks
     *
     * @return the value of boss_pkg_instance.remarks
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_pkg_instance.remarks
     *
     * @param remarks the value for boss_pkg_instance.remarks
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}