package com.chinasofti.rcloud.domain;

import java.io.Serializable;

public class ServiceRportalEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_service_rportal.id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_service_rportal.service_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_service_rportal.manage_url
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String manageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_service_rportal
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_service_rportal.id
     *
     * @return the value of boss_service_rportal.id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_service_rportal.id
     *
     * @param id the value for boss_service_rportal.id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_service_rportal.service_name
     *
     * @return the value of boss_service_rportal.service_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_service_rportal.service_name
     *
     * @param serviceName the value for boss_service_rportal.service_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_service_rportal.manage_url
     *
     * @return the value of boss_service_rportal.manage_url
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getManageUrl() {
        return manageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_service_rportal.manage_url
     *
     * @param manageUrl the value for boss_service_rportal.manage_url
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setManageUrl(String manageUrl) {
        this.manageUrl = manageUrl == null ? null : manageUrl.trim();
    }
}