package com.chinasofti.rcloud.domain;

import java.io.Serializable;

public class SpaceEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_space.space_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String spaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_space.space_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String spaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_space.cf_space_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String cfSpaceGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_space.organization_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_space.cf_org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String cfOrgGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_space.space_chname
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String spaceChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_space.space_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String spaceDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_space
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_space.space_id
     *
     * @return the value of portal_space.space_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_space.space_id
     *
     * @param spaceId the value for portal_space.space_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setSpaceId(String spaceId) {
        this.spaceId = spaceId == null ? null : spaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_space.space_name
     *
     * @return the value of portal_space.space_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getSpaceName() {
        return spaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_space.space_name
     *
     * @param spaceName the value for portal_space.space_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setSpaceName(String spaceName) {
        this.spaceName = spaceName == null ? null : spaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_space.cf_space_guid
     *
     * @return the value of portal_space.cf_space_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getCfSpaceGuid() {
        return cfSpaceGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_space.cf_space_guid
     *
     * @param cfSpaceGuid the value for portal_space.cf_space_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCfSpaceGuid(String cfSpaceGuid) {
        this.cfSpaceGuid = cfSpaceGuid == null ? null : cfSpaceGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_space.organization_id
     *
     * @return the value of portal_space.organization_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_space.organization_id
     *
     * @param organizationId the value for portal_space.organization_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_space.cf_org_guid
     *
     * @return the value of portal_space.cf_org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getCfOrgGuid() {
        return cfOrgGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_space.cf_org_guid
     *
     * @param cfOrgGuid the value for portal_space.cf_org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCfOrgGuid(String cfOrgGuid) {
        this.cfOrgGuid = cfOrgGuid == null ? null : cfOrgGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_space.space_chname
     *
     * @return the value of portal_space.space_chname
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getSpaceChname() {
        return spaceChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_space.space_chname
     *
     * @param spaceChname the value for portal_space.space_chname
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setSpaceChname(String spaceChname) {
        this.spaceChname = spaceChname == null ? null : spaceChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_space.space_description
     *
     * @return the value of portal_space.space_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getSpaceDescription() {
        return spaceDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_space.space_description
     *
     * @param spaceDescription the value for portal_space.space_description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setSpaceDescription(String spaceDescription) {
        this.spaceDescription = spaceDescription == null ? null : spaceDescription.trim();
    }
}