package com.chinasofti.rcloud.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TransactionRecordEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.record_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.account_balance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private BigDecimal accountBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.transaction_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.money_flow
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer moneyFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.transaction_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date transactionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.transaction_amount
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private BigDecimal transactionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer markDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.account_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_transaction_record.description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_transaction_record
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.record_id
     *
     * @return the value of portal_transaction_record.record_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.record_id
     *
     * @param recordId the value for portal_transaction_record.record_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.user_id
     *
     * @return the value of portal_transaction_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.user_id
     *
     * @param userId the value for portal_transaction_record.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.account_balance
     *
     * @return the value of portal_transaction_record.account_balance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public BigDecimal getAccountBalance() {
        return accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.account_balance
     *
     * @param accountBalance the value for portal_transaction_record.account_balance
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setAccountBalance(BigDecimal accountBalance) {
        this.accountBalance = accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.transaction_type
     *
     * @return the value of portal_transaction_record.transaction_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.transaction_type
     *
     * @param transactionType the value for portal_transaction_record.transaction_type
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setTransactionType(Integer transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.money_flow
     *
     * @return the value of portal_transaction_record.money_flow
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getMoneyFlow() {
        return moneyFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.money_flow
     *
     * @param moneyFlow the value for portal_transaction_record.money_flow
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setMoneyFlow(Integer moneyFlow) {
        this.moneyFlow = moneyFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.transaction_time
     *
     * @return the value of portal_transaction_record.transaction_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.transaction_time
     *
     * @param transactionTime the value for portal_transaction_record.transaction_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.transaction_amount
     *
     * @return the value of portal_transaction_record.transaction_amount
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public BigDecimal getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.transaction_amount
     *
     * @param transactionAmount the value for portal_transaction_record.transaction_amount
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setTransactionAmount(BigDecimal transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.mark_delete
     *
     * @return the value of portal_transaction_record.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.mark_delete
     *
     * @param markDelete the value for portal_transaction_record.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.account_id
     *
     * @return the value of portal_transaction_record.account_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.account_id
     *
     * @param accountId the value for portal_transaction_record.account_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_transaction_record.description
     *
     * @return the value of portal_transaction_record.description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_transaction_record.description
     *
     * @param description the value for portal_transaction_record.description
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}