package com.chinasofti.rcloud.domain;

import java.io.Serializable;
import java.util.Date;

public class UserEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.user_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.user_email
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.password
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.mobile_phone
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.create_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer markDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.real_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.company_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.area_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.streat_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String streatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.fixed_phone
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String fixedPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.bank_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.uaa_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String uaaGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.organization_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.cf_org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String cfOrgGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.tenant
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private String tenant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_user.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_user
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.user_id
     *
     * @return the value of portal_user.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.user_id
     *
     * @param userId the value for portal_user.user_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.user_name
     *
     * @return the value of portal_user.user_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.user_name
     *
     * @param userName the value for portal_user.user_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.user_email
     *
     * @return the value of portal_user.user_email
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.user_email
     *
     * @param userEmail the value for portal_user.user_email
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.password
     *
     * @return the value of portal_user.password
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.password
     *
     * @param password the value for portal_user.password
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.mobile_phone
     *
     * @return the value of portal_user.mobile_phone
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.mobile_phone
     *
     * @param mobilePhone the value for portal_user.mobile_phone
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.role_code
     *
     * @return the value of portal_user.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.role_code
     *
     * @param roleCode the value for portal_user.role_code
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.create_time
     *
     * @return the value of portal_user.create_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.create_time
     *
     * @param createTime the value for portal_user.create_time
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.mark_delete
     *
     * @return the value of portal_user.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.mark_delete
     *
     * @param markDelete the value for portal_user.mark_delete
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.real_name
     *
     * @return the value of portal_user.real_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.real_name
     *
     * @param realName the value for portal_user.real_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.company_name
     *
     * @return the value of portal_user.company_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.company_name
     *
     * @param companyName the value for portal_user.company_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.area_name
     *
     * @return the value of portal_user.area_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.area_name
     *
     * @param areaName the value for portal_user.area_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.streat_name
     *
     * @return the value of portal_user.streat_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getStreatName() {
        return streatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.streat_name
     *
     * @param streatName the value for portal_user.streat_name
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setStreatName(String streatName) {
        this.streatName = streatName == null ? null : streatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.fixed_phone
     *
     * @return the value of portal_user.fixed_phone
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getFixedPhone() {
        return fixedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.fixed_phone
     *
     * @param fixedPhone the value for portal_user.fixed_phone
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setFixedPhone(String fixedPhone) {
        this.fixedPhone = fixedPhone == null ? null : fixedPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.bank_account
     *
     * @return the value of portal_user.bank_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.bank_account
     *
     * @param bankAccount the value for portal_user.bank_account
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.uaa_guid
     *
     * @return the value of portal_user.uaa_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getUaaGuid() {
        return uaaGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.uaa_guid
     *
     * @param uaaGuid the value for portal_user.uaa_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setUaaGuid(String uaaGuid) {
        this.uaaGuid = uaaGuid == null ? null : uaaGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.organization_id
     *
     * @return the value of portal_user.organization_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.organization_id
     *
     * @param organizationId the value for portal_user.organization_id
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.cf_org_guid
     *
     * @return the value of portal_user.cf_org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getCfOrgGuid() {
        return cfOrgGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.cf_org_guid
     *
     * @param cfOrgGuid the value for portal_user.cf_org_guid
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setCfOrgGuid(String cfOrgGuid) {
        this.cfOrgGuid = cfOrgGuid == null ? null : cfOrgGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.tenant
     *
     * @return the value of portal_user.tenant
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public String getTenant() {
        return tenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.tenant
     *
     * @param tenant the value for portal_user.tenant
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setTenant(String tenant) {
        this.tenant = tenant == null ? null : tenant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_user.status
     *
     * @return the value of portal_user.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_user.status
     *
     * @param status the value for portal_user.status
     *
     * @mbggenerated Mon Jan 19 10:09:58 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}